### ISSUE TITLE
need to support SurfaceView

### ISSUE THREAD

**Issue by KiminRyu** [rubensousa/PreviewSeekBar#5]
As you know, for playing dash + widevine content, we should use SurfaceView.
I tried to integrate this library, however, It seems woking not well like this.
Here is result for changing surface type to surface_view in your exoplayer_controls.xml.
and same things happen in my application.
![image](https://cloud.githubusercontent.com/assets/7759511/22697040/808d4822-ed93-11e6-973a-9e13eb0312ab.png)

**Comment by KiminRyu** [comment]
http://stackoverflow.com/questions/5647824/android-multiple-surfaceviews

now i am reading this post. It seems helpful for this issue.

**Comment by rubensousa** [comment]
I used a TextureView because of the reasons mentioned in ExoPlayer's FAQ:

https://google.github.io/ExoPlayer/faqs.html#should-i-use-surfaceview-or-textureview
https://google.github.io/ExoPlayer/faqs.html#how-do-i-get-smooth-animationscrolling-of-video

As you can see there:

> To achieve smooth animation or scrolling of video prior to Android N, it’s therefore necessary to use TextureView rather than SurfaceView.

I tried animating the SurfaceView but got some strange issues. 

> As you know, for playing dash + widevine content, we should use SurfaceView.

I didn't know this. Can you provide a source?

**Comment by KiminRyu** [comment]
In 4th line
* Support for secure output when playing DRM protected content.
TextureView cannot play content with DRM.

**Comment by rubensousa** [comment]
Please, check the sample again. Commit https://github.com/rubensousa/PreviewSeekBar/commit/c02e390ecc83e181b313f9b117e8e479725b25ef
should fix this.
